# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=256)),
                ('isbn', models.IntegerField(null=True)),
                ('author', models.CharField(max_length=256)),
                ('small_image_url', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=256, null=True)),
                ('num_pages', models.IntegerField(null=True)),
                ('series_works', models.CharField(max_length=256, null=True)),
                ('publication_year', models.CharField(max_length=256, null=True)),
                ('publication_day', models.CharField(max_length=256, null=True)),
                ('publication_month', models.CharField(max_length=256, null=True)),
                ('rating', models.CharField(max_length=256, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('id', models.CharField(default='0', max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('borrowed_from', models.CharField(max_length=256)),
                ('borrower', models.CharField(max_length=256, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Book')),
                ('loanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_id', to='libraryapp.Book')),
            ],
        ),
    ]
