# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('image', models.URLField(blank=True, null=True)),
                ('date', models.DateField()),
                ('rating', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, null=True)),
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('loanID', models.UUIDField(default=uuid.UUID('a2edf014-6b67-436f-97cb-f7dfa163bbf1'), editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('borrowed_from', models.CharField(max_length=256)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.Book')),
            ],
        ),
    ]
