# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_day',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_month',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='series_works',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='loanID',
        ),
        migrations.AddField(
            model_name='book',
            name='author_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pubday',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pubmonth',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pubyear',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
